// <auto-generated />
using System;
using FinalProject_ABBOTT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_ABBOTT.Migrations
{
    [DbContext(typeof(ContestantsContext))]
    [Migration("20260419141210_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject_ABBOTT.Models.Contestant", b =>
                {
                    b.Property<int>("ContestantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContestantID"), 1L, 1);

                    b.Property<bool>("CheckInStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContestantID");

                    b.ToTable("Contestants");

                    b.HasData(
                        new
                        {
                            ContestantID = 1,
                            CheckInStatus = true,
                            Division = "Computer Programming",
                            Email = "ecarter1@gmail.com",
                            FirstName = "Ethan",
                            LastName = "Carter",
                            RegistrationDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Northeast Community College"
                        },
                        new
                        {
                            ContestantID = 2,
                            CheckInStatus = true,
                            Division = "Web Design and Development",
                            Email = "mlopez2@gmail.com",
                            FirstName = "Maya",
                            LastName = "Lopez",
                            RegistrationDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska–Lincoln"
                        },
                        new
                        {
                            ContestantID = 3,
                            CheckInStatus = false,
                            Division = "Cybersecurity",
                            Email = "jreed3@gmail.com",
                            FirstName = "Jordan",
                            LastName = "Reed",
                            RegistrationDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Wayne State College"
                        },
                        new
                        {
                            ContestantID = 4,
                            CheckInStatus = true,
                            Division = "Health Knowledge Bowl",
                            Email = "anguyen4@gmail.com",
                            FirstName = "Alyssa",
                            LastName = "Nguyen",
                            RegistrationDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Norfolk High School"
                        },
                        new
                        {
                            ContestantID = 5,
                            CheckInStatus = true,
                            Division = "Computer Programming",
                            Email = "bfischer5@gmail.com",
                            FirstName = "Brandon",
                            LastName = "Fischer",
                            RegistrationDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska at Omaha"
                        },
                        new
                        {
                            ContestantID = 6,
                            CheckInStatus = false,
                            Division = "Job Interview",
                            Email = "smartinez6@gmail.com",
                            FirstName = "Sofia",
                            LastName = "Martinez",
                            RegistrationDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Creighton University"
                        },
                        new
                        {
                            ContestantID = 7,
                            CheckInStatus = true,
                            Division = "Welding",
                            Email = "lturner7@gmail.com",
                            FirstName = "Liam",
                            LastName = "Turner",
                            RegistrationDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Mid-Plains Community College"
                        },
                        new
                        {
                            ContestantID = 8,
                            CheckInStatus = false,
                            Division = "Culinary Arts",
                            Email = "cbennett8@gmail.com",
                            FirstName = "Chloe",
                            LastName = "Bennett",
                            RegistrationDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Kearney High School"
                        },
                        new
                        {
                            ContestantID = 9,
                            CheckInStatus = true,
                            Division = "Graphic Communications",
                            Email = "nhughes9@gmail.com",
                            FirstName = "Noah",
                            LastName = "Hughes",
                            RegistrationDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska at Kearney"
                        },
                        new
                        {
                            ContestantID = 10,
                            CheckInStatus = true,
                            Division = "Carpentry",
                            Email = "ecollins10@gmail.com",
                            FirstName = "Emma",
                            LastName = "Collins",
                            RegistrationDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Central Community College"
                        },
                        new
                        {
                            ContestantID = 11,
                            CheckInStatus = true,
                            Division = "Cybersecurity",
                            Email = "lward11@gmail.com",
                            FirstName = "Lucas",
                            LastName = "Ward",
                            RegistrationDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Northeast Community College"
                        },
                        new
                        {
                            ContestantID = 12,
                            CheckInStatus = false,
                            Division = "Job Interview",
                            Email = "iprice12@gmail.com",
                            FirstName = "Isabella",
                            LastName = "Price",
                            RegistrationDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska–Lincoln"
                        },
                        new
                        {
                            ContestantID = 13,
                            CheckInStatus = true,
                            Division = "Automotive Service Technology",
                            Email = "lbell13@gmail.com",
                            FirstName = "Logan",
                            LastName = "Bell",
                            RegistrationDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Wayne State College"
                        },
                        new
                        {
                            ContestantID = 14,
                            CheckInStatus = true,
                            Division = "TeamWorks",
                            Email = "amurphy14@gmail.com",
                            FirstName = "Ava",
                            LastName = "Murphy",
                            RegistrationDate = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Norfolk High School"
                        },
                        new
                        {
                            ContestantID = 15,
                            CheckInStatus = false,
                            Division = "Electrical Construction Wiring",
                            Email = "ebailey15@gmail.com",
                            FirstName = "Elijah",
                            LastName = "Bailey",
                            RegistrationDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska at Omaha"
                        },
                        new
                        {
                            ContestantID = 16,
                            CheckInStatus = true,
                            Division = "Web Design and Development",
                            Email = "hrivera16@gmail.com",
                            FirstName = "Harper",
                            LastName = "Rivera",
                            RegistrationDate = new DateTime(2026, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Creighton University"
                        },
                        new
                        {
                            ContestantID = 17,
                            CheckInStatus = true,
                            Division = "Welding",
                            Email = "jcooper17@gmail.com",
                            FirstName = "James",
                            LastName = "Cooper",
                            RegistrationDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Mid-Plains Community College"
                        },
                        new
                        {
                            ContestantID = 18,
                            CheckInStatus = true,
                            Division = "Culinary Arts",
                            Email = "arichardson18@gmail.com",
                            FirstName = "Amelia",
                            LastName = "Richardson",
                            RegistrationDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Kearney High School"
                        },
                        new
                        {
                            ContestantID = 19,
                            CheckInStatus = false,
                            Division = "Graphic Communications",
                            Email = "bcox19@gmail.com",
                            FirstName = "Benjamin",
                            LastName = "Cox",
                            RegistrationDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska at Kearney"
                        },
                        new
                        {
                            ContestantID = 20,
                            CheckInStatus = true,
                            Division = "Carpentry",
                            Email = "mhoward20@gmail.com",
                            FirstName = "Mia",
                            LastName = "Howard",
                            RegistrationDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Central Community College"
                        },
                        new
                        {
                            ContestantID = 21,
                            CheckInStatus = false,
                            Division = "Computer Programming",
                            Email = "dward21@gmail.com",
                            FirstName = "Daniel",
                            LastName = "Ward",
                            RegistrationDate = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Northeast Community College"
                        },
                        new
                        {
                            ContestantID = 22,
                            CheckInStatus = true,
                            Division = "Cybersecurity",
                            Email = "etorres22@gmail.com",
                            FirstName = "Ella",
                            LastName = "Torres",
                            RegistrationDate = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska–Lincoln"
                        },
                        new
                        {
                            ContestantID = 23,
                            CheckInStatus = true,
                            Division = "Automotive Service Technology",
                            Email = "mpeterson23@gmail.com",
                            FirstName = "Matthew",
                            LastName = "Peterson",
                            RegistrationDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Wayne State College"
                        },
                        new
                        {
                            ContestantID = 24,
                            CheckInStatus = false,
                            Division = "Health Knowledge Bowl",
                            Email = "sgray24@gmail.com",
                            FirstName = "Scarlett",
                            LastName = "Gray",
                            RegistrationDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "Norfolk High School"
                        },
                        new
                        {
                            ContestantID = 25,
                            CheckInStatus = true,
                            Division = "Electrical Construction Wiring",
                            Email = "hjames25@gmail.com",
                            FirstName = "Henry",
                            LastName = "James",
                            RegistrationDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            School = "University of Nebraska at Omaha"
                        });
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"), 1L, 1);

                    b.Property<string>("CoordinatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("EventTime")
                        .HasColumnType("time");

                    b.Property<int>("FilledContestantSlots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalContestantSlots")
                        .HasColumnType("int");

                    b.HasKey("DivisionId");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            DivisionId = 1,
                            CoordinatorName = "Harvey Kingsley",
                            EventTime = new TimeSpan(0, 7, 0, 0, 0),
                            FilledContestantSlots = 13,
                            Name = "Computer Programming",
                            TotalContestantSlots = 20
                        },
                        new
                        {
                            DivisionId = 2,
                            CoordinatorName = "Melissa Grant",
                            EventTime = new TimeSpan(0, 8, 30, 0, 0),
                            FilledContestantSlots = 18,
                            Name = "Web Design and Development",
                            TotalContestantSlots = 18
                        },
                        new
                        {
                            DivisionId = 3,
                            CoordinatorName = "Daniel Ortiz",
                            EventTime = new TimeSpan(0, 9, 0, 0, 0),
                            FilledContestantSlots = 12,
                            Name = "Cybersecurity",
                            TotalContestantSlots = 16
                        },
                        new
                        {
                            DivisionId = 4,
                            CoordinatorName = "Brian Keller",
                            EventTime = new TimeSpan(0, 7, 30, 0, 0),
                            FilledContestantSlots = 20,
                            Name = "Automotive Service Technology",
                            TotalContestantSlots = 24
                        },
                        new
                        {
                            DivisionId = 5,
                            CoordinatorName = "Scott Ramirez",
                            EventTime = new TimeSpan(0, 10, 0, 0, 0),
                            FilledContestantSlots = 14,
                            Name = "Welding",
                            TotalContestantSlots = 15
                        },
                        new
                        {
                            DivisionId = 6,
                            CoordinatorName = "Jason Miller",
                            EventTime = new TimeSpan(0, 8, 0, 0, 0),
                            FilledContestantSlots = 17,
                            Name = "Carpentry",
                            TotalContestantSlots = 20
                        },
                        new
                        {
                            DivisionId = 7,
                            CoordinatorName = "Angela Dupree",
                            EventTime = new TimeSpan(0, 11, 0, 0, 0),
                            FilledContestantSlots = 10,
                            Name = "Culinary Arts",
                            TotalContestantSlots = 12
                        },
                        new
                        {
                            DivisionId = 8,
                            CoordinatorName = "Rachel Nguyen",
                            EventTime = new TimeSpan(0, 9, 30, 0, 0),
                            FilledContestantSlots = 28,
                            Name = "Health Knowledge Bowl",
                            TotalContestantSlots = 30
                        },
                        new
                        {
                            DivisionId = 9,
                            CoordinatorName = "Ethan Brooks",
                            EventTime = new TimeSpan(0, 10, 30, 0, 0),
                            FilledContestantSlots = 9,
                            Name = "Graphic Communications",
                            TotalContestantSlots = 14
                        },
                        new
                        {
                            DivisionId = 10,
                            CoordinatorName = "Lauren Mitchell",
                            EventTime = new TimeSpan(0, 13, 0, 0, 0),
                            FilledContestantSlots = 21,
                            Name = "Job Interview",
                            TotalContestantSlots = 25
                        },
                        new
                        {
                            DivisionId = 11,
                            CoordinatorName = "Kevin O'Connor",
                            EventTime = new TimeSpan(0, 7, 45, 0, 0),
                            FilledContestantSlots = 16,
                            Name = "Electrical Construction Wiring",
                            TotalContestantSlots = 18
                        },
                        new
                        {
                            DivisionId = 12,
                            CoordinatorName = "Derrick Holmes",
                            EventTime = new TimeSpan(0, 8, 15, 0, 0),
                            FilledContestantSlots = 26,
                            Name = "TeamWorks",
                            TotalContestantSlots = 30
                        });
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.School", b =>
                {
                    b.Property<int>("SchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolID"), 1L, 1);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolID");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolID = 1,
                            Location = "Norfolk",
                            SchoolName = "Northeast Community College",
                            SchoolType = "College/PostSecondary"
                        },
                        new
                        {
                            SchoolID = 2,
                            Location = "Lincoln",
                            SchoolName = "University of Nebraska–Lincoln",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 3,
                            Location = "Wayne",
                            SchoolName = "Wayne State College",
                            SchoolType = "College"
                        },
                        new
                        {
                            SchoolID = 4,
                            Location = "Norfolk",
                            SchoolName = "Norfolk High School",
                            SchoolType = "High School"
                        },
                        new
                        {
                            SchoolID = 5,
                            Location = "Omaha",
                            SchoolName = "University of Nebraska at Omaha",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 6,
                            Location = "Omaha",
                            SchoolName = "Creighton University",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 7,
                            Location = "North Platte",
                            SchoolName = "Mid-Plains Community College",
                            SchoolType = "College/PostSecondary"
                        },
                        new
                        {
                            SchoolID = 8,
                            Location = "Kearney",
                            SchoolName = "Kearney High School",
                            SchoolType = "High School"
                        },
                        new
                        {
                            SchoolID = 9,
                            Location = "Kearney",
                            SchoolName = "University of Nebraska at Kearney",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 10,
                            Location = "Grand Island",
                            SchoolName = "Central Community College",
                            SchoolType = "College/PostSecondary"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
