// <auto-generated />
using System;
using FinalProject_ABBOTT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_ABBOTT.Migrations
{
    [DbContext(typeof(ContestantsContext))]
    [Migration("20260425215902_AddIdentityTables")]
    partial class AddIdentityTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject_ABBOTT.Models.Contestant", b =>
                {
                    b.Property<int>("ContestantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContestantID"), 1L, 1);

                    b.Property<bool>("CheckInStatus")
                        .HasColumnType("bit");

                    b.Property<int>("DivisionID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SchoolID")
                        .HasColumnType("int");

                    b.HasKey("ContestantID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("SchoolID");

                    b.ToTable("Contestants");

                    b.HasData(
                        new
                        {
                            ContestantID = 1,
                            CheckInStatus = true,
                            DivisionID = 1,
                            Email = "ecarter1@gmail.com",
                            FirstName = "Ethan",
                            LastName = "Carter",
                            RegistrationDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 1
                        },
                        new
                        {
                            ContestantID = 2,
                            CheckInStatus = true,
                            DivisionID = 2,
                            Email = "mlopez2@gmail.com",
                            FirstName = "Maya",
                            LastName = "Lopez",
                            RegistrationDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 2
                        },
                        new
                        {
                            ContestantID = 3,
                            CheckInStatus = false,
                            DivisionID = 3,
                            Email = "jreed3@gmail.com",
                            FirstName = "Jordan",
                            LastName = "Reed",
                            RegistrationDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 3
                        },
                        new
                        {
                            ContestantID = 4,
                            CheckInStatus = true,
                            DivisionID = 8,
                            Email = "anguyen4@gmail.com",
                            FirstName = "Alyssa",
                            LastName = "Nguyen",
                            RegistrationDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 4
                        },
                        new
                        {
                            ContestantID = 5,
                            CheckInStatus = true,
                            DivisionID = 1,
                            Email = "bfischer5@gmail.com",
                            FirstName = "Brandon",
                            LastName = "Fischer",
                            RegistrationDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 5
                        },
                        new
                        {
                            ContestantID = 6,
                            CheckInStatus = false,
                            DivisionID = 10,
                            Email = "smartinez6@gmail.com",
                            FirstName = "Sofia",
                            LastName = "Martinez",
                            RegistrationDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 6
                        },
                        new
                        {
                            ContestantID = 7,
                            CheckInStatus = true,
                            DivisionID = 5,
                            Email = "lturner7@gmail.com",
                            FirstName = "Liam",
                            LastName = "Turner",
                            RegistrationDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 7
                        },
                        new
                        {
                            ContestantID = 8,
                            CheckInStatus = false,
                            DivisionID = 7,
                            Email = "cbennett8@gmail.com",
                            FirstName = "Chloe",
                            LastName = "Bennett",
                            RegistrationDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 8
                        },
                        new
                        {
                            ContestantID = 9,
                            CheckInStatus = true,
                            DivisionID = 9,
                            Email = "nhughes9@gmail.com",
                            FirstName = "Noah",
                            LastName = "Hughes",
                            RegistrationDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 9
                        },
                        new
                        {
                            ContestantID = 10,
                            CheckInStatus = true,
                            DivisionID = 6,
                            Email = "ecollins10@gmail.com",
                            FirstName = "Emma",
                            LastName = "Collins",
                            RegistrationDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 10
                        },
                        new
                        {
                            ContestantID = 11,
                            CheckInStatus = true,
                            DivisionID = 3,
                            Email = "lward11@gmail.com",
                            FirstName = "Lucas",
                            LastName = "Ward",
                            RegistrationDate = new DateTime(2026, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 1
                        },
                        new
                        {
                            ContestantID = 12,
                            CheckInStatus = false,
                            DivisionID = 10,
                            Email = "iprice12@gmail.com",
                            FirstName = "Isabella",
                            LastName = "Price",
                            RegistrationDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 2
                        },
                        new
                        {
                            ContestantID = 13,
                            CheckInStatus = true,
                            DivisionID = 4,
                            Email = "lbell13@gmail.com",
                            FirstName = "Logan",
                            LastName = "Bell",
                            RegistrationDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 3
                        },
                        new
                        {
                            ContestantID = 14,
                            CheckInStatus = true,
                            DivisionID = 12,
                            Email = "amurphy14@gmail.com",
                            FirstName = "Ava",
                            LastName = "Murphy",
                            RegistrationDate = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 4
                        },
                        new
                        {
                            ContestantID = 15,
                            CheckInStatus = false,
                            DivisionID = 11,
                            Email = "ebailey15@gmail.com",
                            FirstName = "Elijah",
                            LastName = "Bailey",
                            RegistrationDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 5
                        },
                        new
                        {
                            ContestantID = 16,
                            CheckInStatus = true,
                            DivisionID = 2,
                            Email = "hrivera16@gmail.com",
                            FirstName = "Harper",
                            LastName = "Rivera",
                            RegistrationDate = new DateTime(2026, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 6
                        },
                        new
                        {
                            ContestantID = 17,
                            CheckInStatus = true,
                            DivisionID = 5,
                            Email = "jcooper17@gmail.com",
                            FirstName = "James",
                            LastName = "Cooper",
                            RegistrationDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 7
                        },
                        new
                        {
                            ContestantID = 18,
                            CheckInStatus = true,
                            DivisionID = 7,
                            Email = "arichardson18@gmail.com",
                            FirstName = "Amelia",
                            LastName = "Richardson",
                            RegistrationDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 8
                        },
                        new
                        {
                            ContestantID = 19,
                            CheckInStatus = false,
                            DivisionID = 9,
                            Email = "bcox19@gmail.com",
                            FirstName = "Benjamin",
                            LastName = "Cox",
                            RegistrationDate = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 9
                        },
                        new
                        {
                            ContestantID = 20,
                            CheckInStatus = true,
                            DivisionID = 6,
                            Email = "mhoward20@gmail.com",
                            FirstName = "Mia",
                            LastName = "Howard",
                            RegistrationDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SchoolID = 10
                        });
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.Division", b =>
                {
                    b.Property<int>("DivisionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionID"), 1L, 1);

                    b.Property<string>("CoordinatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("EventTime")
                        .HasColumnType("time");

                    b.Property<int>("FilledContestantSlots")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalContestantSlots")
                        .HasColumnType("int");

                    b.HasKey("DivisionID");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            DivisionID = 1,
                            CoordinatorName = "Harvey Kingsley",
                            EventTime = new TimeSpan(0, 7, 0, 0, 0),
                            FilledContestantSlots = 13,
                            Name = "Computer Programming",
                            TotalContestantSlots = 20
                        },
                        new
                        {
                            DivisionID = 2,
                            CoordinatorName = "Melissa Grant",
                            EventTime = new TimeSpan(0, 8, 30, 0, 0),
                            FilledContestantSlots = 18,
                            Name = "Web Design and Development",
                            TotalContestantSlots = 18
                        },
                        new
                        {
                            DivisionID = 3,
                            CoordinatorName = "Daniel Ortiz",
                            EventTime = new TimeSpan(0, 9, 0, 0, 0),
                            FilledContestantSlots = 12,
                            Name = "Cybersecurity",
                            TotalContestantSlots = 16
                        },
                        new
                        {
                            DivisionID = 4,
                            CoordinatorName = "Brian Keller",
                            EventTime = new TimeSpan(0, 7, 30, 0, 0),
                            FilledContestantSlots = 20,
                            Name = "Automotive Service Technology",
                            TotalContestantSlots = 24
                        },
                        new
                        {
                            DivisionID = 5,
                            CoordinatorName = "Scott Ramirez",
                            EventTime = new TimeSpan(0, 10, 0, 0, 0),
                            FilledContestantSlots = 14,
                            Name = "Welding",
                            TotalContestantSlots = 15
                        },
                        new
                        {
                            DivisionID = 6,
                            CoordinatorName = "Jason Miller",
                            EventTime = new TimeSpan(0, 8, 0, 0, 0),
                            FilledContestantSlots = 17,
                            Name = "Carpentry",
                            TotalContestantSlots = 20
                        },
                        new
                        {
                            DivisionID = 7,
                            CoordinatorName = "Angela Dupree",
                            EventTime = new TimeSpan(0, 11, 0, 0, 0),
                            FilledContestantSlots = 10,
                            Name = "Culinary Arts",
                            TotalContestantSlots = 12
                        },
                        new
                        {
                            DivisionID = 8,
                            CoordinatorName = "Rachel Nguyen",
                            EventTime = new TimeSpan(0, 9, 30, 0, 0),
                            FilledContestantSlots = 28,
                            Name = "Health Knowledge Bowl",
                            TotalContestantSlots = 30
                        },
                        new
                        {
                            DivisionID = 9,
                            CoordinatorName = "Ethan Brooks",
                            EventTime = new TimeSpan(0, 10, 30, 0, 0),
                            FilledContestantSlots = 9,
                            Name = "Graphic Communications",
                            TotalContestantSlots = 14
                        },
                        new
                        {
                            DivisionID = 10,
                            CoordinatorName = "Lauren Mitchell",
                            EventTime = new TimeSpan(0, 13, 0, 0, 0),
                            FilledContestantSlots = 21,
                            Name = "Job Interview",
                            TotalContestantSlots = 25
                        },
                        new
                        {
                            DivisionID = 11,
                            CoordinatorName = "Kevin O'Connor",
                            EventTime = new TimeSpan(0, 7, 45, 0, 0),
                            FilledContestantSlots = 16,
                            Name = "Electrical Construction Wiring",
                            TotalContestantSlots = 18
                        },
                        new
                        {
                            DivisionID = 12,
                            CoordinatorName = "Derrick Holmes",
                            EventTime = new TimeSpan(0, 8, 15, 0, 0),
                            FilledContestantSlots = 26,
                            Name = "TeamWorks",
                            TotalContestantSlots = 30
                        });
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.School", b =>
                {
                    b.Property<int>("SchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolID"), 1L, 1);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolID");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            SchoolID = 1,
                            Location = "Norfolk",
                            SchoolName = "Northeast Community College",
                            SchoolType = "College/PostSecondary"
                        },
                        new
                        {
                            SchoolID = 2,
                            Location = "Lincoln",
                            SchoolName = "University of Nebraska–Lincoln",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 3,
                            Location = "Wayne",
                            SchoolName = "Wayne State College",
                            SchoolType = "College"
                        },
                        new
                        {
                            SchoolID = 4,
                            Location = "Norfolk",
                            SchoolName = "Norfolk High School",
                            SchoolType = "High School"
                        },
                        new
                        {
                            SchoolID = 5,
                            Location = "Omaha",
                            SchoolName = "University of Nebraska at Omaha",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 6,
                            Location = "Omaha",
                            SchoolName = "Creighton University",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 7,
                            Location = "North Platte",
                            SchoolName = "Mid-Plains Community College",
                            SchoolType = "College/PostSecondary"
                        },
                        new
                        {
                            SchoolID = 8,
                            Location = "Kearney",
                            SchoolName = "Kearney High School",
                            SchoolType = "High School"
                        },
                        new
                        {
                            SchoolID = 9,
                            Location = "Kearney",
                            SchoolName = "University of Nebraska at Kearney",
                            SchoolType = "University"
                        },
                        new
                        {
                            SchoolID = 10,
                            Location = "Grand Island",
                            SchoolName = "Central Community College",
                            SchoolType = "College/PostSecondary"
                        });
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.Contestant", b =>
                {
                    b.HasOne("FinalProject_ABBOTT.Models.Division", "Division")
                        .WithMany("Contestants")
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_ABBOTT.Models.School", "School")
                        .WithMany("Contestants")
                        .HasForeignKey("SchoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FinalProject_ABBOTT.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FinalProject_ABBOTT.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_ABBOTT.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FinalProject_ABBOTT.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.Division", b =>
                {
                    b.Navigation("Contestants");
                });

            modelBuilder.Entity("FinalProject_ABBOTT.Models.School", b =>
                {
                    b.Navigation("Contestants");
                });
#pragma warning restore 612, 618
        }
    }
}
